### ISSUE TITLE
Columndefs option should accept an observable object

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#11]
So we can autogenerate columns with more refinement

**Comment by ericmbarnard** [comment]
Others have asked about this as well. Even though KoGrid is ko throughout, it still has core logic that relies on options be contsant to the specific grid instance.

I have made the options that can be changed 'on the fly' `observable` in nature, as I do want to support developer's needs in that area. 

However, if changing from `autogeneratecolumns : true` to `autogeneratecolumns : false` is something that you are looking to do, it requires many more fundamental changes to the KoGrid architecture as column generation only takes place during grid initialization.

**Comment by thelinuxlich** [comment]
I thought about this feature because of the need of different custom widths with autogenerated columns. What if the columndefs property accepted as many columns as needed but only use the ones that exist in the data object?

**Comment by ericmbarnard** [comment]
I believe that would break how I've got cell and header templates working currently. Is your use-case essentially that you want to bring back variable data, and you just want it to bind to the grid correctly?

If thats the case, it may not be that expensive (considering the work that would have to be done to support this use case) to just destroy and re-create the grid each time you get different data.

Let me know if that is what your intention is.

**Comment by thelinuxlich** [comment]
The problem is that the autogeneration of columns miscalculate the width for displaying content. For example, a column with the text "RECLAMAÇÕES" gets cut and displays like "RECLAMAÇÕ"

**Comment by ericmbarnard** [comment]
Issue #7 should fix the cutting off of column names. I'm going to fix the calculation that figures out how long a column header name is so that it properly takes care of this

**Comment by ericmbarnard** [comment]
latest push just fixed the column width portion

**Comment by thelinuxlich** [comment]
Problem still persists...look at this example: http://intranet.umc.br/aplic/relatorio_fale_conosco/index.html (try a date period like 01/01/2011 and 01/06/2011 and select some fields)

**Comment by ericmbarnard** [comment]
Wow this looks pretty cool -

Ok, I've got it running - but I need a few more specifics. KoGrid still doesn't support the `columnDefs` being observable, but what exactly is still persisting here?

**Comment by thelinuxlich** [comment]
Sorry Eric! Wrong issue! The problem remains with the column width autocalculation

**Comment by orneryd** [comment]
It now supports it on my fork

https://github.com/Crash8308/sKoGrid/commit/31584f10f4a0e900e77542ae910b1d17a8054472

https://github.com/Crash8308/sKoGrid

**Comment by ericmbarnard** [comment]
Closing as this will be fixed in PR #69 (merging of skogrid)
