### ISSUE TITLE
2.0 issue - sortInfo not being changed on sort

### ISSUE THREAD

**Issue by erikbcox** [Knockout-Contrib/KoGrid#138]
I'm implementing the same sortInfo pattern in 2.0 as in the complex example (http://ericmbarnard.github.com/KoGrid/examples/Complex-Server-Side-Paging.html) for the last version. Sorting isn't triggering a change to the observable. From what I can see useExternalSorting isn't being used at all. I want to be doing the server side sorting/paging. 

If I add self.config.sortInfo(sortInfo); to line 1299 in the self.sortData method the observable will fire. That likely isn't a complete solution though.

**Comment by orneryd** [comment]
this is a duplicate of #131

**Comment by davidjsilva** [comment]
Actually I am having similar issues to @erikbcox.  See this fiddle http://jsfiddle.net/55GKa/19/ for example.  I set useExternalSorting to true but it is still doing a client side search on the grid.  And yes if you search for useExternalSorting in the js code it is never being used other than being initialized in the defaults object.

**Comment by orneryd** [comment]
you mention useExternalSorting, do you mean useExternalFiltering? because filtering has to do with search, not sorting.

As for the sorting, there was a bug that is fixed in the latest build that fixes the flag useExternalSorting if set to true it will not sort when you click the header row.

the sortinfo problem persists though. trying to make it two-way + initial sorting state when user defined.

**Comment by erikbcox** [comment]
I am trying to sort. I just tested with the latest update and it still isn't working. 
Here is how I changed the sortData method...

 self.sortData = function (col, direction) {
        self.isSorting = true;
        sortInfo = {
            column: col,
            direction: direction
        };
        self.clearSortingData(col);

```
    if(!self.config.useExternalSorting){
        kg.sortService.Sort(sortInfo, self.sortedData);
    }
    else{
        self.config.sortInfo(sortInfo);
    }
    self.lastSortedColumn = col;
    self.searchProvider.evalFilter();
    self.isSorting = false;
};
```

I still want everything to happen except the client sort (clearing etc). The UI arrows need to be on the last column I've sorted and the sortInfo observable that is passed into the options needs to change so the computed observable fires and does the server side sort.
