### ISSUE TITLE
style binding column width not working

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#88]
knockout's 'style' binding handler sets style in the following manner:

``` javascript
element.style[styleName] = styleValue || "";
```

In javascript, when setting a 'width' style using element.style['width'] it must be in length units ie "##px".  So unfortunately style: { width: $parent.columns()[{1}].width } doesn't work because its trying to assign a number ie 100 instead of "100px".  This is causing the header cells to not have a proper width assigned.

For what it's worth, if you change to style: { width: $parent.columns()[{1}].width() + \'px\' } it works perfectly.  However, is it safe to assume that width is in pixels??  Not sure, maybe it is.

**Comment by orneryd** [comment]
what browser are you seeing the behavior on?

**Comment by davidjsilva** [comment]
I've tested in Chrome 22.0.1229.94 and Firefox 15.0.1

**Comment by orneryd** [comment]
I am not seeing any issues in Chrome 22.0.1229.94 Chrome 24.0.1290.1 , Firefox 15.0.1 and Firefox 16.0.1

columnDef

```
{ field: 'InboundTransaction', displayName: 'In/Out', width: 50}
```

Showing width in chrome:
http://i.imgur.com/ecAbm.png
Firefox:
http://i.imgur.com/GY5tD.png

**Comment by orneryd** [comment]
can you provide a jsFiddle to reproduce the problem you are seeing?

**Comment by orneryd** [comment]
I am closing the issue for now since I can't repro it. If you can give me a jsfiddle where you have reproduced the problem feel free to comment and we will re-open the issue

**Comment by davidjsilva** [comment]
Hey buddy sorry for the delayed response was on a 3 day vacation.  I've included some screenshots which show that width style isn't being applied.  Here is the jsfiddle - http://jsfiddle.net/8V629/1/

http://i.imgur.com/SdIY2.jpg
http://i.imgur.com/IAKrP.jpg

I'm on Windows 7

**Comment by orneryd** [comment]
I'm still not seeing what you are seeing. I am seeing a different issue where the pager buttons are in the wrong place, but that is unrelated to the column width  ( which is rendering properly in your fiddle on my screen.)

**Comment by davidjsilva** [comment]
OK so I updated the jsfiddle to more accurately reflect what is going on - http://jsfiddle.net/8V629/5/. I pasted the kogrid Master branch CSS into the CSS window in jsfiddle because for some reason it wasn't working when I added it as a Managed Resource.

Also, please check this image http://i.imgur.com/AuR8k.jpg where I've highlighted the issues.

You'll notice that the first column width ( ie Reference ) should be 150 but it is 167px.  And the other columns are off as well.  Also the HTML isn't getting an inline style width applied to it.

Thanks again for looking into this.

Note: disregard the pager buttons in the wrong place, that's a separate unrelated issue

**Comment by orneryd** [comment]
No, problem. I found other bugs which I fixed in the latest commit. version 1.2.1 Can you try using that version and see if it fixes your issues?

**Comment by davidjsilva** [comment]
OK tried the new version and still having the same issues - http://jsfiddle.net/8V629/11/.  For what it's worth I've seen other people reporting issues with setting width/height with a number without the units.  

http://stackoverflow.com/questions/349861/javascript-style-width-not-working-in-firefox-with-transitional-doctype
http://stackoverflow.com/questions/557747/how-to-set-div-width-height-with-javascript-in-firefox
http://stackoverflow.com/questions/4667651/javascript-set-element-width-or-height-in-standards-mode

So maybe something like style: { width: $parent.columns()[{1}].width() + \'px\' } would work in all browsers??

**Comment by orneryd** [comment]
Ok, I was finalyl able to see what you were talking about. I went ahead and tested it with your change and am fixing it now.

**Comment by davidjsilva** [comment]
Thanks for making those changes.  Although I think issue #88 still has an issue.  This fiddle is still not getting the width applied to it - http://jsfiddle.net/8V629/11/.

I think it's because $parent.columns()[0].width evaluates to an observable and therefore cannot complete the concatenation of 'px'.  I think it needs to be $parent.columns()[0].width() to actually get the value of width (notice the parentheses).

**Comment by orneryd** [comment]
actually, changing that goes back to the original behavior, it does get the concatenation because the observable is evaluated

**Comment by davidjsilva** [comment]
OK so it was still not working for me so I updated the fiddle to include the knockout-debug js so that I can troubleshoot it some more.  If you look at http://i.imgur.com/GGx6L.jpg you'll notice that I've set a breakpoint within the style binding.  A couple things to notice here:
1. after it tries to assign the width style, the width style is still empty
2. The value of styleValue is an observable function and should be the width with the units (ie ###px).  Yes it tried to unwrapObservable but because we are doing a concatenation it doesn't unwrap the observable correctly.

Also if you take a look at http://i.imgur.com/yaOyq.jpg the inline style width was not applied and the width of the column is still larger than its supposed to be ie 150px.

With that said, is there something I'm doing wrong here?  I modified the 1.2.1 js and deployed to my test server and did the $parent.columns()[0].width() and it actually works as expected.  See fiddle http://jsfiddle.net/9Sgf7/3/ and image http://i.imgur.com/czHLw.jpg.  As you can see the width is correctly being applied.

Let me know what you think.  Thanks again for your prompt replies.
