### ISSUE TITLE
Bug when updating the columnDefs observableArray 

### ISSUE THREAD

**Issue by lhope** [Knockout-Contrib/KoGrid#94]
Hi there. I have a bug with the current version of KoGrid: 
2f0093638a21dda8d151b6b36360abfa7ac8409e

The problem is when I take advantage of observable columnDefs to redefine the grid. It happens when displaySelectionCheckbox and displayResults are set to true (the default).

It looks like the code at Grid.js:434-439 is being called at each change to add the rowIndex and **kg_selected** fields.

Example:
In my code, I am each time constructing a new defs array and then calling columnDefs(defs);

Change to fields:- id, NOUN, TYPE.
defs:

``` javascript
[{"field":"id"},{"field":"NOUN"},{"field":"TYPE"}]
```

columnDefs:

``` javascript
[{"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"id","displayName":"id","sortable":true,"resizable":true,"filterable":true},
 {"field":"NOUN","displayName":"NOUN","sortable":true,"resizable":true,"filterable":true},
 {"field":"TYPE","displayName":"TYPE","sortable":true,"resizable":true,"filterable":true}]
```

Change back to fields:- id
defs: 

``` javascript
[{"field":"id"}]
```

columnDefs:

``` javascript
[{"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"id","displayName":"id","sortable":true,"resizable":true,"filterable":true}]
```

And so on:- id, NOUN, TYPE
defs:

``` javascript
[{"field":"id"},{"field":"NOUN"},{"field":"TYPE"}]
```

columnDefs:

``` javascript
[{"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"rowIndex","width":25,"displayName":"rowIndex","sortable":true,"resizable":true,"filterable":true},
 {"field":"__kg_selected__","width":25,"displayName":"__kg_selected__","sortable":true,"resizable":true,"filterable":true},
 {"field":"id","displayName":"id","sortable":true,"resizable":true,"filterable":true},
 {"field":"NOUN","displayName":"NOUN","sortable":true,"resizable":true,"filterable":true},
 {"field":"TYPE","displayName":"TYPE","sortable":true,"resizable":true,"filterable":true}]
```

**Comment by orneryd** [comment]
fixed in latest commit

**Comment by lhope** [comment]
This isn't really fixed. See pull request #96 which I think fixes the issue.
